// Automatically generated by prebuild.js. Do not edit manually.
export const prebuiltSettings = {
  companyName: "iModules",
  logoUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&h=120&q=80"
};
